standalone_tags:
  [
    {id: 1, size: 0.0522},
    {id: 2, size: 0.0522},
    {id: 3, size: 0.0522},
    {id: 4, size: 0.0522},
    {id: 0, size: 0.0522}
  ]
tag_bundles:
  [
    {
      name: 'power_station_tag',
      layout:
        [
          {id: 0, size: 0.0522, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 1, size: 0.0522, x: 0.0916, y: 0.0583, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 2, size: 0.0522, x: 0.0916, y: -0.0583, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 3, size: 0.0522, x: -0.0916, y: -0.0583, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 4, size: 0.0522, x: -0.0916, y: 0.0583, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    }
  ]
